import Head from "next/head";
import Image from "next/image";
import Burger from "../components/Burger";
import Card from "../components/Card";

export default function Home() {

  let f = "";

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Welcome to React with <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Image src="/logo.png" width={200} height={200} alt="" />

        <p className="description">
          Get started by editing <code className="code">pages/index.js</code>
        </p>

        <Burger burgers={10} />

        <div className="grid">
          <Card link="https://nextjs.org/docs" 
                title="Documentation"
                text="Find in-depth information about Next.js features and API." />
          
          <Card link="https://nextjs.org/learn"
                title="Learn"
                text="Learn about Next.js in an interactive course with quizzes!"/>

          <Card link="https://github.com/vercel/next.js/tree/canary/examples"
                title="Examples"
                text="Discover and deploy boilerplate example Next.js projects."/>

          <Card link="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                title="Deploy"
                text="Instantly deploy your Next.js site to a public URL with Vercel."/>
        </div>
      </main>
      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
